### ISSUE TITLE
Did you try to make it a cat file ?

### ISSUE THREAD

**Issue by UmeSiyah** [hkaramian/RobustVideoMatting-For-Nuke#1]
Hello,

I wonder if you have tried to [make a cat file for your gizmo ?](https://learn.foundry.com/nuke/content/reference_guide/air_nodes/catfilecreator.html)

**Comment by hkaramian** [comment]
Hello, 
Yes I know about cattery and how much easier to use it would be. But to convert RVM to cat file we need to convert it to TorchScript first, and it's not easy! Another issue, RVM is an RNN model, we can't implement RNNs using cattery.

**Comment by UmeSiyah** [comment]
Ok, thank you for the answer !
