### ISSUE TITLE
Linux Compatibilty

### ISSUE THREAD

**Issue by Saku241** [hkaramian/RobustVideoMatting-For-Nuke#4]
Hey did you think about linux compatibility for the node ? 
The check dependencies ever tells no python but I installed everything with miniconda3

**Comment by bmossm** [comment]
Assuming that you installed everything in the created environment like in the instructions?

**Comment by Saku241** [comment]
Yep i followed all the instructions but the node is pointing to a python.exe

**Comment by hkaramian** [comment]
Hey guys, I believe It's not compatible with linux, as there are a couple of functions that run through cmd (bash) and that commands need to be updated to works in linux. 

I hope I give an update in future and make it linux compatible

**Comment by bmossm** [comment]
The node should point to the python inside the miniconda3 environment.
If it installed in the default directory the one listed in the node is correct. If the python for the km_rvm environment is somewhere else (like hkaramian mentioned in another issue#, C:\Program Data\... if you installed for "All Users") then you will need to add your own path.

**Comment by Saku241** [comment]
> The node should point to the python inside the miniconda3 environment. If it installed in the default directory the one listed in the node is correct. If the python for the km_rvm environment is somewhere else (like hkaramian mentioned in another issue#, C:\Program Data... if you installed for "All Users") then you will need to add your own path.

Thanks but this issue is for LINUX compatibility as it shown above. 

As @hkaramian said, there is functions that runs through cmd and you can’t just simply point python on linux

**Comment by bmossm** [comment]
GOTCHA. Definitely read your question as asking about Linux, knowing it wouldn't work, and then an issue you were having separately.
Cheers.
